# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 10:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Complexities',
            },
        ),
        migrations.CreateModel(
            name='ProjectManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Completed', models.BooleanField(default=False)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('Comments', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'ProjectManagementActivities',
            },
        ),
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Activity')),
            ],
            options={
                'verbose_name_plural': 'RequestTypes',
            },
        ),
        migrations.CreateModel(
            name='SetArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'SetAreas',
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.PositiveIntegerField()),
                ('Name', models.CharField(max_length=256)),
                ('Activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Activity')),
            ],
            options={
                'verbose_name_plural': 'Steps',
            },
        ),
        migrations.CreateModel(
            name='SubProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Active', models.BooleanField()),
                ('CreatedDate', models.DateTimeField(auto_now_add=True)),
                ('LastUpdated', models.DateTimeField(auto_now=True)),
                ('Name', models.CharField(max_length=256, null=True)),
                ('Details', models.CharField(blank=True, max_length=1000)),
                ('Deadline', models.DateField(blank=True, null=True)),
                ('AdjustedDeadline', models.DateField(blank=True, null=True)),
                ('Completed', models.DateField(blank=True, null=True)),
                ('Comments', models.CharField(blank=True, max_length=1000)),
                ('Activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.Activity')),
                ('Categories', models.ManyToManyField(blank=True, to='Demand.Category')),
                ('Complexity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.Complexity')),
                ('ForSetArea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.SetArea')),
                ('Priority', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.BusinessPriority')),
                ('Project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.Project')),
                ('Requestor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Requestor', to=settings.AUTH_USER_MODEL)),
                ('Specialist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specialist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'SubProjects',
            },
        ),
        migrations.CreateModel(
            name='SubStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'SubStatuses',
            },
        ),
        migrations.AddField(
            model_name='subproject',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engagement.SubStatus'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='Step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engagement.Step'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.RequestType'),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='Step',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engagement.Step'),
        ),
        migrations.AddField(
            model_name='projectmanagement',
            name='SubProject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engagement.SubProject'),
        ),
    ]
