# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complexity',
            options={'verbose_name_plural': 'Complexities'},
        ),
        migrations.AlterModelOptions(
            name='projectmanagement',
            options={'verbose_name_plural': 'ProjectManagementActivities'},
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={'verbose_name_plural': 'RequestTypes'},
        ),
        migrations.AlterModelOptions(
            name='setarea',
            options={'verbose_name_plural': 'SetAreas'},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'verbose_name_plural': 'Steps'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'verbose_name_plural': 'SubProjects'},
        ),
        migrations.AlterModelOptions(
            name='substatus',
            options={'verbose_name_plural': 'SubStatuses'},
        ),
    ]
