# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 10:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0002_auto_20170712_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='Active',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Categories',
            field=models.ManyToManyField(blank=True, to='Demand.Category'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Complexity',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.Complexity'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Details',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='ForSetArea',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.SetArea'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Priority',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.BusinessPriority'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Specialist',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specialist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.RequestType'),
        ),
    ]
