# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 11:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0005_auto_20170712_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='Complexity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.Complexity'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='ForSetArea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.SetArea'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Name',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.Project'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.BusinessPriority'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Specialist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Specialist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='Type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Engagement.RequestType'),
        ),
    ]
