# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0012_auto_20170711_1356'),
        ('Engagement', '0006_auto_20170712_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='Activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.Activity'),
        ),
    ]
