# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0007_subproject_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='Parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprojects', to='Demand.Project'),
        ),
    ]
