# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-12 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0008_auto_20170712_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subproject',
            name='Parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.Project'),
        ),
    ]
