# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-13 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0010_auto_20170713_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmanagement',
            old_name='ProjectId',
            new_name='SubProject',
        ),
    ]
