# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 10:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Spend', models.FloatField()),
                ('Savings', models.FloatField()),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('LastUpadate', models.DateTimeField()),
                ('Comments', models.CharField(max_length=1000)),
                ('Actions', models.CharField(max_length=255)),
                ('BusinessPriority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.BusinessPriority')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='Risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Risk'),
        ),
        migrations.AddField(
            model_name='project',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Status'),
        ),
        migrations.AddField(
            model_name='country',
            name='Projects',
            field=models.ManyToManyField(to='Demand.Project'),
        ),
        migrations.AddField(
            model_name='country',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Region'),
        ),
        migrations.AddField(
            model_name='category',
            name='Projects',
            field=models.ManyToManyField(to='Demand.Project'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Projects',
            field=models.ManyToManyField(to='Demand.Project'),
        ),
    ]
