# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-07 10:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Description', models.CharField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='BusinessPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'BusinessPriorities',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.IntegerField()),
                ('Name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=256)),
                ('Spend', models.FloatField(blank=True, default=0)),
                ('Savings', models.FloatField(blank=True, default=0)),
                ('StartDate', models.DateField(verbose_name='Project Start Date')),
                ('EndDate', models.DateField(verbose_name='Project End Date')),
                ('LastUpadate', models.DateTimeField(auto_now=True)),
                ('Comments', models.CharField(blank=True, max_length=1000)),
                ('Actions', models.CharField(blank=True, max_length=255)),
                ('Activities', models.ManyToManyField(blank=True, related_name='activities', to='Demand.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Statuses',
            },
        ),
        migrations.CreateModel(
            name='UserAssosiation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='BusinessContacts',
            field=models.ManyToManyField(blank=True, related_name='BusinessContacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='BusinessPartners',
            field=models.ManyToManyField(blank=True, related_name='BusinessPartners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='BusinessPriority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.BusinessPriority', verbose_name='Business Priority'),
        ),
        migrations.AddField(
            model_name='project',
            name='Categories',
            field=models.ManyToManyField(blank=True, to='Demand.Category'),
        ),
        migrations.AddField(
            model_name='project',
            name='Countries',
            field=models.ManyToManyField(blank=True, to='Demand.Country'),
        ),
        migrations.AddField(
            model_name='project',
            name='Owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='Risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Risk'),
        ),
        migrations.AddField(
            model_name='project',
            name='Status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Status'),
        ),
        migrations.AddField(
            model_name='country',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Region'),
        ),
        migrations.AddField(
            model_name='activity',
            name='Manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
