# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectToCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='Projects',
        ),
        migrations.AddField(
            model_name='projecttocategory',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Category'),
        ),
        migrations.AddField(
            model_name='projecttocategory',
            name='Project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.Project'),
        ),
    ]
