# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0002_auto_20170707_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name_plural': 'Statuses'},
        ),
    ]
