# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 12:10
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Demand', '0005_auto_20170707_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssosiation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('BusinessContacts', models.ManyToManyField(blank=True, related_name='BusinessContacts', to=settings.AUTH_USER_MODEL)),
                ('BusinessPartners', models.ManyToManyField(blank=True, related_name='BusinessPartners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
