# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-07 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0006_userassosiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassosiation',
            name='BusinessContacts',
            field=models.ManyToManyField(blank=True, related_name='BusinessContacts', to='Demand.Project'),
        ),
        migrations.AlterField(
            model_name='userassosiation',
            name='BusinessPartners',
            field=models.ManyToManyField(blank=True, related_name='BusinessPartners', to='Demand.Project'),
        ),
    ]
