# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0007_auto_20170707_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='Projects',
        ),
        migrations.RemoveField(
            model_name='country',
            name='Projects',
        ),
        migrations.AddField(
            model_name='project',
            name='Categories',
            field=models.ManyToManyField(blank=True, to='Demand.Category'),
        ),
        migrations.AddField(
            model_name='project',
            name='Countries',
            field=models.ManyToManyField(blank=True, to='Demand.Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='BusinessPriority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demand.BusinessPriority', verbose_name='Business Priority'),
        ),
        migrations.AlterField(
            model_name='project',
            name='EndDate',
            field=models.DateField(verbose_name='Project End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='StartDate',
            field=models.DateField(verbose_name='Project Start Date'),
        ),
    ]
