# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0008_auto_20170711_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='Projects',
        ),
        migrations.AddField(
            model_name='project',
            name='Activities',
            field=models.ManyToManyField(blank=True, to='Demand.Activity'),
        ),
    ]
