# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-11 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0010_auto_20170711_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='LastUpadate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
