# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Demand', '0012_auto_20170711_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassosiation',
            name='BusinessContacts',
        ),
        migrations.RemoveField(
            model_name='userassosiation',
            name='BusinessPartners',
        ),
        migrations.AddField(
            model_name='activity',
            name='Manager',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='BusinessContacts',
            field=models.ManyToManyField(blank=True, related_name='BusinessContacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='BusinessPartners',
            field=models.ManyToManyField(blank=True, related_name='BusinessPartners', to=settings.AUTH_USER_MODEL),
        ),
    ]
