# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-17 09:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0013_auto_20170717_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='Manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
