# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Engagement', '0012_projectmanagement_completed'),
        ('Survey', '0004_auto_20170803_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Engagement.SubProject')),
                ('QeustionSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Survey.QuestionSet')),
            ],
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='Answer',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='Engagement',
        ),
        migrations.RemoveField(
            model_name='surveyanswer',
            name='Question',
        ),
        migrations.DeleteModel(
            name='SurveyAnswer',
        ),
        migrations.AddField(
            model_name='answer',
            name='Survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Survey.Survey'),
        ),
    ]
