# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Survey', '0005_auto_20170809_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='QeustionSet',
            new_name='QuestionSet',
        ),
    ]
