# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Demand', '0015_auto_20170724_1552'),
        ('Survey', '0006_auto_20170809_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionset',
            name='DefaultFor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Demand.Activity'),
        ),
    ]
